version: "3.8"
services:
  service-db:
    environment:
      POSTGRES_PASSWORD: pwd
    image: postgres:11
    ports:
      - 5432:5432
  service:
    build: .
    command: /bin/sh -c "./migrate && ./service"
    environment:
      - RUST_BACKTRACE=1
      - PORT=3000
      - PG_CONN_STRING=postgres://postgres:pwd@service-db:5432/postgres
    ports:
      - 3000:3000
    depends_on:
      - service-db
