{
 "title": "Service metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Application metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS by Service [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(response_code[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "HTTP Response code by status [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum(rate(response_code{namespace=\"meredian\",statuscode=~\"[23]..\"}[1m])) by (statuscode) * 60",
     "legendFormat": "OK: {{statuscode}}"
    },
    {
     "expr": "sum(rate(response_code{namespace=\"meredian\",statuscode=~\"4..\"}[1m])) by (statuscode) * 60",
     "legendFormat": "Req Error: {{statuscode}}"
    },
    {
     "expr": "sum(rate(response_code{namespace=\"meredian\",statuscode=~\"5..\"}[1m])) by (statuscode) * 60",
     "legendFormat": "Server Error:: {{statuscode}}"
    }
   ]
  },
  {
   "title": "Request latency in ms [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum (rate(response_time_bucket[1m])) by (le)) * 1000",
     "legendFormat": "50% quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum (rate(response_time_bucket[1m])) by (le)) * 1000",
     "legendFormat": "95% quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(response_time_bucket[1m])) by (le)) * 1000",
     "legendFormat": "99% quantile"
    },
    {
     "expr": "histogram_quantile(1, sum (rate(response_time_bucket[1m])) by (le)) * 1000",
     "legendFormat": "Longest req"
    }
   ]
  },
  { "title": "Postgres application metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Row operations (rows/s) [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "row/s" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{namespace=\"meredian\",datname=\"myapp-db\"}[1m])",
     "legendFormat": "Rows inserted"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{namespace=\"meredian\",datname=\"myapp-db\"}[1m])",
     "legendFormat": "Rows updated"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted{namespace=\"meredian\",datname=\"myapp-db\"}[1m])",
     "legendFormat": "Rows deleted"
    },
    {
     "expr": "rate(pg_stat_database_tup_fetched{namespace=\"meredian\",datname=\"myapp-db\"}[1m])",
     "legendFormat": "Rows fetched"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned{namespace=\"meredian\",datname=\"myapp-db\"}[1m])",
     "legendFormat": "Rows returned"
    }
   ]
  },
  {
   "title": "Transactions (trx/s) [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "trx/s" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{namespace=\"meredian\",datname=\"myapp-db\"}[1m])",
     "legendFormat": "Commited"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{namespace=\"meredian\",datname=\"myapp-db\"}[1m])",
     "legendFormat": "Rollback"
    }
   ]
  },
  { "title": "Kubernetes application metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Cluster CPU used (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[1m])) / sum(machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "CPU usage by app pods (cpu, stacked) [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"meredian\",container!=\"POD\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage by app pods (stacked) [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"meredian\",container!=\"POD\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cluster Mem usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss)/ sum(machine_memory_bytes) * 100"
    },
    {}
   ]
  }
 ]
}