apiVersion: batch/v1
kind: Job
metadata:
  namespace: meredian
  name: migrate-job
  labels:
    app: migrate-job
spec:
  template:
    metadata:
      name: migrate-job
      labels:
        app: migrate-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migrate
        env:
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                # Created by HELM installation
                name: postgres-postgresql
                key: postgresql-password
          - name: PG_CONN_STRING
            value: "postgresql://$(DATABASE_USERNAME):$(DATABASE_PASSWORD)@postgres-postgresql:5432/$(DATABASE_NAME)"
        envFrom:
          - configMapRef:
              name: config-k3
          - secretRef:
              name: db-secret-k3
        image: meredian/otus-microservices:k3-service
        command: ["./migrate"]
  backoffLimit: 100
